### ISSUE TITLE
[QUESTION]编辑工作流

### ISSUE THREAD

**Issue by liqiang-fit2cloud** [rackshift/rackshift#17]
在编辑工作流的页面中
![image](https://user-images.githubusercontent.com/20766823/111566236-c3f0f900-87d7-11eb-9ec4-deeca2c71002.png)
1. 那个“状态”是什么意思？
2. 为什么确定按钮是禁用的？

**Comment by rackshift** [comment]
1.状态 表示是否可以被工作流执行器执行
2.系统提供的工作流不允许修改，用户可以在工作流模板的基础上创建自己的工作流，这样才能编辑
