### ISSUE TITLE
[FEATURE]希望支持centos7 minimal版本

### ISSUE THREAD

**Issue by nondevops** [rackshift/rackshift#23]
**请描述您的需求或者改进建议.**
希望支持centos7 minimal版本

**请描述你建议的实现方案**
背景：当前平台只支持centos7 完整版，完整版给服务器带来了空间压力，造成了不必要的空间资源浪费。因此建议支持centos7 minimal版本

**Comment by rackshift** [comment]
您好，已经收到您的需求，经过分析技术上不存在问题，已经加入排期了。

**Comment by rackshift** [comment]
v1.1.0 已经支持

**Comment by rackshift** [comment]
![image](https://user-images.githubusercontent.com/66816207/115520005-4c255b00-a2bc-11eb-93a6-3d3a9194caa8.png)
您可以进入帮助文档下载这个精简版系统进行安装，这个是在官网精简版基础之上加入了我们系统必要的 rpm 包之后定制的，您可以在此基础上再定制
https://docs.rackshift.io/iso/
