### ISSUE TITLE
能否在自动设置BMC的账号跟密码[FEATURE]

### ISSUE THREAD

**Issue by GuoYingLong** [rackshift/rackshift#31]
**请描述您的需求或者改进建议.**
能否让用户自行设定一个BMC的带外管理账号跟密码。

因为超微的机器，目前BMC的带歪管理口密码都是随机的，能不能进入最小化系统的时候自动设置一个账号跟密码，这样RackShift能更快速的抓到设备信息。

或者进入最小化系统后，先推送到服务端IP地址，以及SN号等网络信息，这样能更快速的在服务端看到机器上线了

**请描述你建议的实现方案**

**Comment by zhangdahai112** [comment]
这个完全可以实现，以前我们就调研过，我们后面排期去做。但是您需要注意以下几个问题：
1.如果需要让最小化系统（RAMOS）来做这件事，那么首先机器必须是 PXE 启动，那么第一次 PXE 启动是需要人为触发的，因为 RackShift 这个时候是不知道带外账号密码的。
2.如果需要 RackShift 来触发第一次 PXE 启动，那么在设置账号密码之前，RackShitf 必须先录入机器的带外账号密码，这就互相矛盾了

**Comment by GuoYingLong** [comment]
正常的服务器，如果没有安装操作系统，首次开机，默认应该会是PXE启动的

**Comment by GuoYingLong** [comment]
也就是说，咱们RackShift需要开一个BMC的参数，设置引导选项，装完系统后默认硬盘启动

**Comment by zhangdahai112** [comment]
ipmitool -I lanplus -H xxx -U xxx -P xxx chassis bootdev pxe
ipmitool -I lanplus -H xxx -U xxx -P xxx chassis power reset
此条命令也只对下一次重启生效，只有下一次重启才会 PXE，装完系统后 ks 文件默认会重启机器的

**Comment by king8609** [comment]
自动发现拓扑，且可以随意拖动大小。如果有交换机，服务器器告警。然后增加一下cpu.io等图型化就更好。Ui美化、
