### ISSUE TITLE
[BUG] 主动发现时报错

### ISSUE THREAD

**Issue by bubbleatgit** [rackshift/rackshift#32]
**RackShift 版本**
Docker安装的 `Release v1.4.0`

**截图**
![image](https://user-images.githubusercontent.com/7858776/130221206-fd5a1d68-94f2-4743-a8ed-e567da2f5d34.png)

**Comment by zhangdahai112** [comment]
提供下您的机器型号

**Comment by bubbleatgit** [comment]
已找到问题所在。
---
由于未按照官网的安装方式安装，导致如下图的IP为空。
![image](https://user-images.githubusercontent.com/7858776/130226252-ef67511a-9286-4c5b-888e-587fa6b28066.png)


---

手动修复可以直接修改配置文件 ` /opt/rackshift/rackhd/monorail/config.json` , 把 `tftpBindAddress` 的值修改为部署 rackshift 的服务器的 IP ：
```
    "tftpBindAddress": "0.0.0.0",
    "tftpBindPort": 69,
    "tftpRoot": "./static/tftp",
    "wssSsl": false,
    "wssBindAddress": "0.0.0.0",
    "wssBindPort": 9100

```

**Comment by zhangdahai112** [comment]
是的

**Comment by bubbleatgit** [comment]
已经可以成功引导
![image](https://user-images.githubusercontent.com/7858776/130398951-f36a0f4e-e7ab-48fe-995a-8b8871daeb42.png)
